# QuickShot config
timeLimit: 90
maxArena: 1
spawn:
  - 0
  - 0
  - 0
maps:
  1:
    sign:
      - 0
      - 0
      - 0
    1:
      - 0
      - 0
      - 0
    2:
      - 0
      - 0
      - 0
    3:
      - 0
      - 0
      - 0
    4:
      - 0
      - 0
      - 0
    5:
      - 0
      - 0
      - 0
    6:
      - 0
      - 0
      - 0